### ISSUE TITLE
btdata gives an error in a 4 column data frame if the winner is always player 1

### ISSUE THREAD

**Issue by crazygambit** [EllaKaye/BradleyTerryScalable#1]
I have my data arranged with player 1 always either winning or drawing, which gives the following error when calling btdata; Error in (function (cl, name, valueClass)  : 
  assignment of an object of class “numeric” is not valid for @‘Dim’ in an object of class “dgTMatrix”; is(value, "integer") is not TRUE

If there are some ties or a few sparse wins for player 2 then you get the following error:

Error in dimnames(mat2) <- list(new_mat2_rownames, new_mat2_colnames) : 
  'dimnames' applied to non-array

**Comment by EllaKaye** [comment]
Hi. I'm happy to get to the bottom of this (or help you do so). To help me do that, could you please send me a reproducible example, including (a subset of) your data or a toy dataset so that I can recreate the problems. [This](https://www.tidyverse.org/help/) is a useful guide to creating reprexes. The [reprex](http://reprex.tidyverse.org) package is really helpful for this. 

Could you please also let me know which version of the `Matrix` package you have installed.

**Comment by crazygambit** [comment]
Thanks for your quick reply. A simple 8 person tournament will throw an error if the results are arranged so player 1 is always the winner, like this:

[Tournament 1.xlsx](https://github.com/EllaKaye/BradleyTerryScalable/files/1441440/Tournament.1.xlsx)


player1 | player2 | pl1result | pl2result
-- | -- | -- | --
A | B | 1 | 0
C | D | 1 | 0
E | F | 1 | 0
G | H | 1 | 0
A | C | 1 | 0
E | G | 1 | 0
E | A | 1 | 0

That will throw the first error. If I add more tournaments that contain draws I get the second error. For example if I have every player in the tournament have a tie against a virtual average player (to avoid giving the winner an infinite rating) and add those rows at the end, I get the second error. Even if I interweave the rows of the second data frame on the first so there aren't too many zeroes in a row, I still get the second error. If I change the order of a few players like for example:

[Tournament 2.xlsx](https://github.com/EllaKaye/BradleyTerryScalable/files/1441463/Tournament.2.xlsx)

player1 | player2 | pl1result | pl2result
-- | -- | -- | --
A | B | 1 | 0
C | D | 1 | 0
F | E | 0 | 1
G | H | 1 | 0
A | C | 1 | 0
E | G | 1 | 0
A | E | 0 | 1

It works perfectly. However making those changes for my whole dataset will prove a bit harder.

I suspect reordering the toy dataset so the winner is always player 1 (which is the way most tournament results are reported) will produce the same error, but I haven't checked.

I'm not on my main machine so I can't look at what version of the Matrix package I have at the moment, but I installed everything this week, so it should be the latest. 

Thanks again for your help.

**Comment by EllaKaye** [comment]
Hi. Thanks for the examples, and for alerting me to the problem. 

For Tournament 1, the way around this is to delete the pl2result column. It doesn't contain any wins data, so has nothing to contribute to the wins matrix or graph. If you then run `btdata` on the remaining 3 column data frame, it'll run fine and give you what you need.

I also think I've identified and worked out how to fix the problem causing the second error. It'll be a few days though, I'm afraid, before I have a chance to double check that and push the fix up here (along with a fix to catch the edge case causing the first error).

**Comment by crazygambit** [comment]
Thanks for the prompt response.

Tournament 1 was just a subset of the data I used because it showed the error message more clearly, my real data has draws and thousands of entries, so using 3 columns won't work. What I did as a work around is swap the players and results on odd rows. Since I know player 1 either wins or draws, this way I make sure I won't have any consecutive zeroes in any column and btdata works as expected.

**Comment by EllaKaye** [comment]
Hi. I've pushed an update to GitHub which should fix the two issues that you raised. 

You can install the updated package with
`library(devtools)`
`install_github("EllaKaye/BradleyTerryScalable")`

If that doesn't work on your full data set, or if you have any further problems, please do let me know.
