### ISSUE TITLE
Adding zero to diagonal?

### ISSUE THREAD

**Issue by Selbosh** [EllaKaye/BradleyTerryScalable#2]
https://github.com/EllaKaye/BradleyTerryScalable/blob/624198ba61be023bfd10a94f593f82c10adc6a94/R/vcov.btfit.R#L7

Aren't the diagonal entries of `wmat` [equal to zero](https://github.com/EllaKaye/BradleyTerryScalable/blob/624198ba61be023bfd10a94f593f82c10adc6a94/src/btprob_vec.cpp#L28)? In which case, does the last term on this line have any effect?

Sorry if I am misunderstanding this.

**Comment by EllaKaye** [comment]
Hi @Selbosh. I think you're right, but best double check with @DavidFirth, since he wrote the vcov_vec code. The fitted.btfit function does put the observed values back on the diagonal, but fitted_vec doesn't.

**Comment by Selbosh** [comment]
Filed pull request https://github.com/EllaKaye/BradleyTerryScalable/pull/3
